environment:
  matrix:
    - PYTHON: "C:\\Python37"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"

install:
  - "%PYTHON%\\python.exe -m pip install --upgrade pip"
  - "%PYTHON%\\python.exe -m pip install wheel"
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"

build: off
build_script:
  - "%WITH_ENV% %PYTHON%\\python.exe setup.py build_ext --inplace"
  - "%WITH_ENV% %PYTHON%\\python.exe setup.py bdist_wheel"

test: off
test_script:
  - "%PYTHON%\\python.exe setup.py test"

artifacts:
  - path: dist\*
